apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-app
  template:
    metadata:
      labels:
        app: boilerplate-app
    spec:
      containers:
        - name: boilerplate
          image: boilerplate:latest
          ports:
            - containerPort: 8080
          env:
            - name: SAMPLE_ENV_VAR
              valueFrom:
                configMapKeyRef:
                  name: boilerplate-cfg
                  key: sample_env_var
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-svc
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8080":"boilerplate-backend-conf"}}'
spec:
  selector:
    app: boilerplate-app
  ports:
  - port:  8080
    targetPort:  8080
  type:  NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boilerplate-cfg
  labels:
    app: boilerplate
data:
  sample_env_var: "sample_env_val"